baseURL = 'https://github.com/lioouzzz/sleepblog.git'
languageCode ="en-us"
title = 'ğŸ€ğŸ€ğŸ€'
paginate = 10
theme = 'ananke'
paginatePath = "page" 

[params]
text_color = ""
author = "Elaine Liu"
favicon = "images/20241130%20å€‹äººlogo2.png"
site_logo = "images/20241130%20å€‹äººlogo2.png"
description = "ç¨‹å¼å­¸ç¿’ç­†è¨˜ï¼Œä¸€äº›lilicodecode><"

# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image = "/images/cover_image.png" 
featured_image_class = "cover bg-center"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-washed-green-60"
recent_posts_number = 10
date_format = "2006å¹´1æœˆ2æ—¥"
background_color_class = "bg-washed-green"


[taxonomies]
  category = "categories"
  tag = "tags"

[pagination]
pagerSize = 10

[[menu.main]]
  identifier = "home"
  name = "é¦–é "
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "tags"
  name = "æ–‡ç« æ¨™ç±¤"
  url = "/tags/"
  weight = 3


[[menu.main]]
  identifier = "categories"
  name = "æ–‡ç« åˆ†é¡"
  url = "/categories/"
  weight = 3

[[menu.main]]
  identifier = "post"
  name = "å…¨éƒ¨æ–‡ç« "
  url = "/posts/"
  weight = 3

[markup.tableOfContents]
    startLevel = 2        # å¾ <h2> é–‹å§‹
    endLevel = 6          # åˆ° <h6> çµæŸ
    ordered = false       # ç„¡åºåˆ—è¡¨
    wrap = "nav"          # åŒ…è£¹ TOC çš„ HTML æ¨™ç±¤
    anchorClass = "toc-anchor"  # éŒ¨é»éˆæ¥çš„ CSS é¡åˆ¥
    noClasses = false     # å…è¨±æ·»åŠ  CSS é¡åˆ¥


custom_css = ["custom.css"]
