baseURL = 'https://github.com/lioouzzz/sleepblog.git'
languageCode ="en-us"
title = 'ğŸ€ğŸ€ğŸ€'
theme = 'ananke'


[params]
text_color = ""
author = ""
favicon = ""
site_logo = "images/20241130%20å€‹äººlogo.png"

description = "The last theme you'll ever need. Maybe."

# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-washed-green"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-center"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-washed-green-60"
